site_name: Pi-Apps Docs
theme:
  name: material
  logo: 'https://github.com/Botspot/pi-apps/blob/master/icons/logo.png?raw=true'
  favicon: 'https://github.com/Botspot/pi-apps/blob/master/icons/logo.png?raw=true'
  palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - scheme: slate
        primary: red
        accent: red
        toggle:
          icon: material/weather-night
          name: Switch to light mode

repo_name: Pi-Apps-Coders/docs
repo_url: https://github.com/Pi-Apps-Coders/docs
edit_uri: https://github.com/Pi-Apps-Coders/docs/edit/master/docs/
